### PR TITLE
added MeasureUnits,Length,Width,Height  to Product UI  (needed for sh…

### PR DESCRIPTION
**Pull request by alexdoan102**
added MeasureUnits,Length,Width,Height  to Product UI  needed for shipping module.
==> this will useful for usps/fedex/ups shipping module. 

(will be used in the new https://goshippo.com/ shipping module...coming soon)

### CODE REVIEW

**Comment by alexdoan102** [comment]
please see screenshot below... this is how it looks on the ProductUI

measureunitsadded

**Comment by tatarincev** [comment]
Egis need to check code and  duplicate this commit to vc-module-catalog

**Comment by mikhaill** [comment]
Hi. We noticed from the notes you're planning on using Shippo for the shipping module. If you have any questions, please feel free to email us at support@goshippo.com and we will be happy to help with the integration.

**Comment by Woland2k** [comment]
@mikhaill thanks, this integration module is developed by @alexdoan102, I'll let him know to contact you if he has any questions. Would you be able to feature our ecommerce platform on your site once integration is complete?

**Comment by mikhaill** [comment]
@Woland2k Yes, there are definitely things we can do to promote the integration. Please email me mikhail@goshippo.com to connect.

**Pull request closed without merging**
